# -*- coding: utf-8 -*-
"""Desicion Tree Classifier and Random Forrest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xqk5Ryf-erBFgt_ZrOXRitLVO6PbMxnG
"""

import os
import pandas as pd
from sklearn.model_selection import train_test_split

def load_data():
    dfs_a = []
    for file in os.listdir('data/training/training_setA'):
        if file.endswith('.psv'):
            df = pd.read_csv(f'data/training/training_setA/{file}', sep='|')
            df['patient_id'] = file.replace('.psv', '')
            dfs_a.append(df)

    dfs_b = []
    for file in os.listdir('data/training/training_setB'):
        if file.endswith('.psv'):
            df = pd.read_csv(f'data/training/training_setB/{file}', sep='|')
            df['patient_id'] = file.replace('.psv', '')
            dfs_b.append(df)

    data = pd.concat(dfs_a + dfs_b, ignore_index=True)

    patient_ids = data['patient_id'].unique()
    train_ids, test_ids = train_test_split(patient_ids, test_size=0.2, random_state=42)
    train_ids, val_ids = train_test_split(train_ids, test_size=0.1, random_state=42)

    train = data[data['patient_id'].isin(train_ids)]
    val = data[data['patient_id'].isin(val_ids)]
    test = data[data['patient_id'].isin(test_ids)]

    return train, val, test

from datasetup import load_data

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    f1_score,
    recall_score,
    precision_score
)

train, val, test = load_data()

features = ['HR', 'O2Sat', 'Temp', 'Resp', 'Age', 'ICULOS']

train_clean = train[features + ['SepsisLabel']].dropna()
val_clean = val[features + ['SepsisLabel']].dropna()
test_clean = test[features + ['SepsisLabel']].dropna()

X_train = train_clean[features]
y_train = train_clean['SepsisLabel']

X_val = val_clean[features]
y_val = val_clean['SepsisLabel']

X_test = test_clean[features]
y_test = test_clean['SepsisLabel']

model = DecisionTreeClassifier(
    max_depth=5,
    random_state=42,
    class_weight='balanced'
)

model.fit(X_train, y_train)

preds = model.predict(X_val)
probs = model.predict_proba(X_val)[:, 1]

print("\n--- Decision Tree Metrics (Validation) ---")
print(f"Accuracy:  {model.score(X_val, y_val):.4f}")
print(f"Precision: {precision_score(y_val, preds):.4f}")
print(f"Recall:    {recall_score(y_val, preds):.4f}")
print(f"F1 Score:  {f1_score(y_val, preds):.4f}")
print(f"ROC-AUC:   {roc_auc_score(y_val, probs):.4f}")
print("\nFull Report:")
print(classification_report(y_val, preds, target_names=['No Sepsis', 'Sepsis']))
print("Confusion Matrix:")
print(confusion_matrix(y_val, preds))

test_preds = model.predict(X_test)
test_probs = model.predict_proba(X_test)[:, 1]

print("\n--- Decision Tree Metrics (Test) ---")
print(f"Accuracy:  {model.score(X_test, y_test):.4f}")
print(f"Precision: {precision_score(y_test, test_preds):.4f}")
print(f"Recall:    {recall_score(y_test, test_preds):.4f}")
print(f"F1 Score:  {f1_score(y_test, test_preds):.4f}")
print(f"ROC-AUC:   {roc_auc_score(y_test, test_probs):.4f}")
print("\nFull Report:")
print(classification_report(y_test, test_preds, target_names=['No Sepsis', 'Sepsis']))
print("Confusion Matrix:")
print(confusion_matrix(y_test, test_preds))

from datasetup import load_data

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    f1_score,
    recall_score,
    precision_score
)

train, val, test = load_data()

features = ['HR', 'O2Sat', 'Temp', 'Resp', 'Age', 'ICULOS']

train_clean = train[features + ['SepsisLabel']].dropna()
val_clean = val[features + ['SepsisLabel']].dropna()
test_clean = test[features + ['SepsisLabel']].dropna()

X_train = train_clean[features]
y_train = train_clean['SepsisLabel']

X_val = val_clean[features]
y_val = val_clean['SepsisLabel']

X_test = test_clean[features]
y_test = test_clean['SepsisLabel']

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1,
    verbose=1,
    class_weight='balanced'
)

model.fit(X_train, y_train)

preds = model.predict(X_val)
probs = model.predict_proba(X_val)[:, 1]

print("\n--- Random Forest Metrics (Validation) ---")
print(f"Accuracy:  {model.score(X_val, y_val):.4f}")
print(f"Precision: {precision_score(y_val, preds):.4f}")
print(f"Recall:    {recall_score(y_val, preds):.4f}")
print(f"F1 Score:  {f1_score(y_val, preds):.4f}")
print(f"ROC-AUC:   {roc_auc_score(y_val, probs):.4f}")
print("\nFull Report:")
print(classification_report(y_val, preds, target_names=['No Sepsis', 'Sepsis']))
print("Confusion Matrix:")
print(confusion_matrix(y_val, preds))

test_preds = model.predict(X_test)
test_probs = model.predict_proba(X_test)[:, 1]

print("\n--- Random Forest Metrics (Test) ---")
print(f"Accuracy:  {model.score(X_test, y_test):.4f}")
print(f"Precision: {precision_score(y_test, test_preds):.4f}")
print(f"Recall:    {recall_score(y_test, test_preds):.4f}")
print(f"F1 Score:  {f1_score(y_test, test_preds):.4f}")
print(f"ROC-AUC:   {roc_auc_score(y_test, test_probs):.4f}")
print("\nFull Report:")
print(classification_report(y_test, test_preds, target_names=['No Sepsis', 'Sepsis']))
print("Confusion Matrix:")
print(confusion_matrix(y_test, test_preds))